### ISSUE TITLE
No Longer Works

### ISSUE THREAD

**Issue by ahqsoftwares** [Techie-Pi/firebase-scrypt-rust#1]
**Describe the bug**
The crate no longer works with Firebase Auth

**To Reproduce**

**Expected behavior**

**Additional context or information**

**Comment by Techie-Pi** [comment]
Could you give a more detailed description of what "no longer works" means?

**Comment by ahqsoftwares** [comment]
Yeah, basically when I use the library with the password hash (directly copy pasted) into the method verify_password it throws the following error: GenerateDerivedKeyFailed

I suspect it is that the encoding method for the currently firebase base64 has changed as in base64 to txt too, the hashes and salts doesn't work at all

**Comment by ahqsoftwares** [comment]
I am too searching for a solution, if I find I shall certainly make a PR

**Comment by ahqsoftwares** [comment]
Also, sorry for the less detailed description as at that time of creating the issue, I was kinda frustrated

**Comment by Techie-Pi** [comment]
> I suspect it is that the encoding method for the currently firebase base64 has changed as in base64 to txt too, the hashes and salts doesn't work at all

Yeah, looks like it... I don't have much time to research right now, but if you make any findings feel free to make a PR or to post them here :)

> Also, sorry for the less detailed description as at that time of creating the issue, I was kinda frustrated

Don't worry about it, we're here to help each other and learn

**Comment by ahqsoftwares** [comment]
@Techie-Pi Actually I fixed it, Making a PR

**Comment by Techie-Pi** [comment]
Reopening until I publish the new version

**Comment by Techie-Pi** [comment]
Done: [firebase-scrypt 0.2.1](https://crates.io/crates/firebase-scrypt/0.2.1)

Thank you very much for your help! 😄
